### ISSUE TITLE
Android issue RegisterForPushNotificationsResultData with 8.3.10 version

### ISSUE THREAD

**Issue by lbonamini** [Pushwoosh/pushwoosh-phonegap-plugin#383]
Hi there,
when we try to compile with the new version of plugin (8.3.10) we receive this is error:

>  /Users/vagrant/git/platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:23: error: cannot find symbol
> import com.pushwoosh.RegisterForPushNotificationsResultData;
>                     ^
>   symbol:   class RegisterForPushNotificationsResultData
>   location: package com.pushwoosh
> /Users/vagrant/git/platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:179: error: cannot find symbol
> 			Pushwoosh.getInstance().registerForPushNotifications(new Callback<RegisterForPushNotificationsResultData, RegisterForPushNotificationsException>() {
> 			                                                                  ^
>   symbol:   class RegisterForPushNotificationsResultData
>   location: class PushNotifications
> /Users/vagrant/git/platforms/android/app/src/main/java/com/pushwoosh/plugin/pushnotifications/PushNotifications.java:181: error: cannot find symbol
> 				public void process(@NonNull final Result<RegisterForPushNotificationsResultData, RegisterForPushNotificationsException> result) {
> 				                                          ^
>   symbol: class RegisterForPushNotificationsResultData

**Comment by wfhm** [comment]
@lbonamini Checking it.

**Comment by wfhm** [comment]
@lbonamini I could not reproduce it in a new Cordova project (tried it with cordova-android:10.1.2 and cordova-android:11.0.0), so could you please elaborate on this issue? What is your environment and what are the steps to reproduce it?
