### ISSUE TITLE
Issue from Google Review

### ISSUE THREAD

**Issue by xale76** [Pushwoosh/pushwoosh-phonegap-plugin#347]
![Immagine](https://user-images.githubusercontent.com/7335952/114151052-044a1f80-991d-11eb-96fa-930c14480ddd.png)

Hello I've received this from Google. What's happening?

**Comment by wfhm** [comment]
Fixed with 8.1.1 release, please update you plugin version when submitting your app to the store.

**Comment by xale76** [comment]
the problem is that this version uses AndroidX and my app fails building because uses other plugins incompatible. Is there another solution?

**Comment by xale76** [comment]
more...if I build with androidX flag and also plugin android x adapter I got

C:\ProgettiAndroid\APP_USER_CORDOVA\platforms\android\app\src\main\java\com\pushwoosh\plugin\internal\PhonegapPluginProvider.java:3: error: package com.pushwoosh.internal does not exist
import com.pushwoosh.internal.PluginProvider;
                             ^

**Comment by wfhm** [comment]
@xale76 can you share the exact steps to reproduce the build issue?

**Comment by wfhm** [comment]
> the problem is that this version uses AndroidX and my app fails building because uses other plugins that are incompatible with AndroidX even if they're at latest version. Is there another solution?
Our Android SDK does not use old Android Support libs anymore, so all new Cordova plugin versions will use AndroidX, and there is no way for us to release a plugin version that complies with the new Play Store policy with old Android Support libs.

**Comment by guv3n** [comment]
Hi @wfhm 
We're using pushwoosh on our app built with Cordova. 
After getting the same email and our app being removed, I updated the [pushwoosh plugin](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin) to 8.1.1 and resubmitted our app.
It got rejected again. 
The reasons for the first rejection were only mentionning Pushwoosh SDK code. So I guess it's still a problem with the SDK (I didn't get further information from Google..)

**Comment by boredom2** [comment]
@guv3n I can confirm, that 8.1.1 solves the Issue - our App was accepted by Google without any further Issues after updating PW to 8.1.1 (and therefore, updating the android implementations to 6.2.7)

**Comment by guv3n** [comment]
I'm struggling to understand what causes the rejection as I didn't get any further details by email from Google. I guess I have no other choice than to contact them.

**Comment by wfhm** [comment]
@guv3n, Our demo application was accepted by the Store as well, so this is really strange. We have contacted Google Play developer support team as well, I will share their response here once there is any.

**Comment by guv3n** [comment]
To ensure I properly built my app with the updated version of the plugin I removed the Android platform from my cordova project and added it back. I then rebuilt it and sent it for review. 
It got rejected again. 
I did not have answers from Google yet. Really annoyed.
Did you have more chance @wfhm ?

**Comment by wfhm** [comment]
@guv3n no luck so far. Can you create a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new and share the APK that was rejected after updating the APK so we could check if we can find anything suspicious?

**Comment by guv3n** [comment]
Ticket created !

**Comment by wfhm** [comment]
I have checked the APK and there are no methods responsible for collecting lists of applications or packages in .dex files of the APK (the methods are listed below):

    android.content.pm.PackageManager.getInstalledApplications()

    android.content.pm.PackageManager.getInstalledPackages()

@guv3n do you mind if we continue the discussion of your case via the support ticket thread? The issue @xale76 has is a build issue so we strayed away from the original topic a little.

@xale76 were you able to resolve the build issue? If not, could you please share the list of the plugins that conflict with AndroidX libraries? What version of **cordova-android** is used in your project?

**Comment by cmeray** [comment]
Hello, we are having the same issue. We resubmitted using 8.1.1 and it got rejected.

**Comment by wfhm** [comment]
@cmeray @guv3n @xale76 

Could it be that you have APKs/AABs with the old Pushwoosh plugin versions integrated in other releases in the Google Play Console (like in alpha- or beta-testing tracks)? It looks like Expo had [the same issue with Branch SDK in 2019](https://forums.expo.io/t/app-removed-from-google-play-due-to-policy-violation-with-branch/21240), and, for the apps that were still rejected after updating their SDK they suggested checking the following:

> * Ensure you have put an updated apk in every release track for your app, not just the production track
> * Check to make sure you don’t have any old builds containing branch in your alpha, beta and internal tracks

Do you think it could be your case?

**Comment by guv3n** [comment]
I indeed had other tracks with previous versions of the app but I paused them. 
There's no way (or I didn't find) to delete APK from the library.
Today I created new releases for these tracks to ensure the latest version of the APK is used...
It's under review.. No news from Google, unsurprisingly.

**Comment by guv3n** [comment]
That was it ! 
All good 👍

**Comment by wfhm** [comment]
@cmeray @xale76

Any chance it is the same issue for you guys?
