### ISSUE TITLE
Can't compile with iOS 6.0 target

### ISSUE THREAD

**Issue by pbrisson** [Pushwoosh/pushwoosh-phonegap-plugin#44]
Hi there,

I get this error when I'm trying to compile the plugin for iOS 6.0:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CLBeaconRegion", referenced from:
      objc-class-ref in Pushwoosh(PWBeaconsTracker.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried to fallback to commit 657487d, but it don't seem to help.

Any idea?

Thanks!
